### Create product
POST http://localhost:8082/api/products
Content-Type: application/json

{
  "name": "Ipad pro 9",
  "description": "Ipad pro 9 from Apple",
  "price": 1298.99,
  "category": "Electronics",
  "stockQuantity": 80,
  "imageUrl": "",
  "createAt": "2023-07-02T09:00:00.000Z",
  "updateAt": "2025-07-03T09:00:00.000Z"
}


###

