### update product
PUT http://localhost:8082/api/products/b8817bdd-dffc-4667-b54b-d0cf5b949b2f
Content-Type: application/json

{
  "name": "Ipad pro 12",
  "description": "Ipad pro 12 from Apple",
  "price": 1398.99,
  "category": "Electronics",
  "stockQuantity": 80,
  "imageUrl": "",
  "createAt": "2023-07-02T09:00:00.000Z",
  "updateAt": "2025-07-03T09:00:00.000Z"
}
